### ISSUE TITLE
Please add support for R# 2017.1.2

### ISSUE THREAD

**Issue by th3ragex** [sheitmann/AgentSmith#14]
AgentSmith is missing in the R# Extension Manager plugin list.

**Comment by sheitmann** [comment]
I take a look this week.

**Comment by sheitmann** [comment]
I published a version vor R#2017.1 and R#2017.2.
Sorry that it arrived that late.

**Comment by NLI-KelbyHunt** [comment]
No apologies needed @sheitmann 
Thanks for your support!
