### ISSUE TITLE
Allow a way to deactivate documentation warning for Tests project

### ISSUE THREAD

**Issue by bhugot** [sheitmann/AgentSmith#15]
Hello,

There should be a way to deactivate once for all the documentation warning for Tests project.

Maybe there is a way but didn't found

**Comment by sheitmann** [comment]
@bhugot 
at the moment there is no way to deactivate it for test projects.
however I can add an option where you can specify a regex for the name of the projects you want to exlude.
whould this work for you?

**Comment by bhugot** [comment]
Yes totally

**Comment by sheitmann** [comment]
I uploaded a new version. The options page for the general xml documentation settings contains a new text field where you can specify regex patterns for the project names you want to ignore.

please note that the pattern is case sensitive

**Comment by bhugot** [comment]
I will try tomorrow thanks

**Comment by bhugot** [comment]
Sorry forgot to say it s perfect tanks
