### ISSUE TITLE
2020.3 Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [sheitmann/AgentSmith#17]
It's that time again!  Out of 16 extensions that I have installed, this and TestCop were the only extensions that are not available for 2020.3.

---

Please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by sheitmann** [comment]
@Mike-E-angelo 
I uploaded a new version to the plugin repository which should be available soon (is verified by Jetbrains). Let me know when you have issues.
Can you tell me what features you are using from AgentSmith?

**Comment by Mike-E-angelo** [comment]
Awesome, thank you for the quick response @sheitmann!  As for the features I use (and dig!), it's mostly the nifty actions around documentation that I use the most, when I use them. :)

**Comment by GvmiHasan** [comment]
@sheitmann you used wave 202 which is for ReSharper 2020.2 not 2020.3 so it isn't available in Extension Manager.
and i must mention that spell checking in this extension is better than ReSharper internal spell checking, at least i think so 😊
thanks dude 🌹

**Comment by sheitmann** [comment]
@GvmiHasan 
thanks for the info. I removed 2020.3.0 and uploaded 2020.3.1 where wave is now 203. Should be available soon.
