### ISSUE TITLE
Suspend/Resume ReSharper 2021.2 Appears to Hange/Crash with Agent Smith Installed

### ISSUE THREAD

**Issue by Mike-E-angelo** [sheitmann/AgentSmith#18]
Greetings,

I wanted to make sure you are aware of this issue:
https://youtrack.jetbrains.com/issue/RSRP-484699#focus=Comments-27-5108403.0-0

It appears that when Agent Smith is installed and one Suspends/Resumes R# 2021.2, Visual Studio hangs and eventually crashes/restarts.  This has happened several times to me now.  After uninstalling Agent Smith I was able to suspend/resume without hang.

There may be another consideration/factor here, and will update here if so, but I wanted to make sure you are aware of at least the exception that is occurring and if possible see if it can be addressed.

**Comment by sheitmann** [comment]
Hi Mike-E,

thanks for the information. I was not aware of it but I will take a look whats going on.

Br
Sven

**Comment by sheitmann** [comment]
@Mike-E-angelo 
please try this version and let me know if it works. I had no exceptions so far.
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=132192

should be available via plugin manager soon too

**Comment by Mike-E-angelo** [comment]
I can confirm things seem much better now!  Thank you for the quick fix @sheitmann !
