### ISSUE TITLE
Feature request: Ability to ignore specific identifier requiring meta-tag.

### ISSUE THREAD

**Issue by Neonalig** [sheitmann/AgentSmith#19]
Often times when documenting methods, you use words such as 'this' without intending to talk about the base class. (such as in the example below)
![image](https://user-images.githubusercontent.com/16698604/145581863-3c2e54ce-b545-4f53-b7ff-3fb62530bdb5.png)

Adding the ability to ignore 'WordCanBeSurroundedWithMetaTags' for <b><i>specific</i></b> words (i.e. 'this') would greatly enhance the user experience as they are no longer forced to wrap the word in ```<c></c>``` to indicate the identifier is not intended, or to add a comment suppression. This would perhaps be implemented as an 'identifier suggestion blacklist', allowing users to specify words they almost certainly don't want hints for, and can simply add the meta-tag themselves if required without being warned.

**Comment by Neonalig** [comment]
This issue is intended as a feature request.

**Comment by sheitmann** [comment]
@Neonalig 
There is already an option for this. Go to the ReSharper Options and below Tools -> AgenSmith -> XML Documentation -> General you will find "Regular Expression patterns to ignore for metatagging". When you add "this" to the list, it will not be highlighted anymore.
![grafik](https://user-images.githubusercontent.com/1215764/211199694-13d600cf-2801-4f52-a9ae-98c03fa1e63a.png)
