### ISSUE TITLE
Meta-tag suggestions aren't present if preceding meta-tag exists.

### ISSUE THREAD

**Issue by Neonalig** [sheitmann/AgentSmith#20]
Perhaps as a form of optimisation, Agent Smith appears to not suggest meta-tags after a meta-tag is first found in the documentation. This however forces users to add meta-tags manually back-to-front otherwise suggestions disappear.

1. Two suggestions are present.
![image](https://user-images.githubusercontent.com/16698604/145582982-df30e5df-74c5-43ce-96a2-d377765574f0.png)
2.a If the first suggestion is used, the second disappears. 
![image](https://user-images.githubusercontent.com/16698604/145583375-a71ccada-9d1c-4b87-9f06-822a82ad18a4.png)
2.b If the second suggestion is used, the first suggestion still stays. 
![image](https://user-images.githubusercontent.com/16698604/145583116-4aead26f-f258-4bb3-9d6b-14e9a6e86223.png)

This forces users to always implement suggestions in reverse order.

**Comment by sheitmann** [comment]
@Neonalig 
The bug should be fixed in version 2022.3.0-pre01.
