### ISSUE TITLE
Update for 2022.2?

### ISSUE THREAD

**Issue by Huntk23** [sheitmann/AgentSmith#21]
Just wanted to say that I miss this extension. Would love to see it revived again.

**Comment by sheitmann** [comment]
@Huntk23 
There is a version for 2022.2 however it is marked as pre-release. You can activate pre-releases from the resharper options.
However I will release a new version without the pre-release tag this week. 

https://plugins.jetbrains.com/plugin/11653-agent-smith/versions/Prerelease/176545

**Comment by Huntk23** [comment]
I had no idea there was a way to see prerelease packages! Thanks @sheitmann!
