### ISSUE TITLE
2024.2 Support 😊

### ISSUE THREAD

**Issue by Mike-E-angelo** [sheitmann/AgentSmith#24]
Greetings, R# 2024.2 is released and this is the only remaining extension that I have out of a dozen where it's not supported.  Thank you for any effort you can provide in updating this. 🙏

**Comment by sheitmann** [comment]
Hello Mike-E-angelo,

I published a new version on jetbrains pluging hub. It is a prerelease, so make sure to activate that option when looking for it. Please check it out and let me know when you find issues.

It should be available in a few days after Jetbrains has verified it.
Direct download link is https://plugins.jetbrains.com/plugin/download?rel=true&updateId=600218

Regards
Sven

**Comment by Mike-E-angelo** [comment]
I can confirm that this is now available in R#.  Thank you for taking the time to update @sheitmann. 🙏
