### ISSUE TITLE
C# 6 string interpolation support

### ISSUE THREAD

**Issue by th3ragex** [sheitmann/AgentSmith#7]
Marking a string with the `'$'` sign seems to exclude the whole string from spellchecking.

Example: 
`var errorCode = 42;`
`var message = $"The errror code was {errorCode}!";`

The equivalent with `string.Format` works as expected.

Used environment:
.Net 4.5.1 Project
VS15 Update 2 (14.0.25123.00)
R# 2016.1.2
Agent Smith 2016.1.0

**Comment by sheitmann** [comment]
thanks for reporting, I take a look into it

**Comment by sheitmann** [comment]
added in 2016.1.1 and 2016.2.1-rc
